export const foods = [
    {
        id: 1,
        image: "/Image-2.png",
        description: "Spicy seasoned seafood noodles ",
        price: "$ 2.29",
        bowl: "20",
        orderType: "Dine In",
        category: "Hot Dishes",
    },
    {
        id: 2,
        image: "/Image-2.png",
        description: "Salted Pasta with mushroom sauce ",
        price: "$ 2.69",
        bowl: "11",
        orderType: "Dine In",
        category: "Hot Dishes",
    },
    {
        id: 3,
        image: "/Image-3.png",
        description: "Beef dumpling in hot and sour soup ",
        price: "$ 2.99",
        bowl: "16",
        orderType: "Dine In",
        category: "Soup",
    },
    {
        id: 4,
        image: "/Image-5.png",
        description: "Healthy noodle with spinach leaf ",
        price: "$ 3.29",
        bowl: "22",
        orderType: "To go",
        category: "Cold Dishes",
    },
    {
        id: 5,
        image: "/Image-5.png",
        description: "Hot spicy fried rice with omelet ",
        price: "$ 3.49",
        bowl: "13",
        orderType: "Delivery",
        category: "Hot Dishes",
    },
    {
        id: 6,
        image: "/Image-6.png",
        description: "Spicy instant noodle with special omelette ",
        price: "$ 3.59",
        bowl: "17",
        orderType: "To go",
        category: "Hot Dishes",
    },
    {
        id: 7,
        image: "/Image-2.png",
        description: "Spicy seasoned seafood noodles ",
        price: "$ 2.29",
        bowl: "20",
        orderType: "Dine In",
        category: "Hot Dishes",
    },
    {
        id: 8,
        image: "/Image-2.png",
        description: "Salted Pasta with mushroom sauce ",
        price: "$ 2.69",
        bowl: "11",
        orderType: "Dine In",
        category: "Hot Dishes",
    },
    {
        id: 9,
        image: "/Image-3.png",
        description: "Beef dumpling in hot and sour soup ",
        price: "$ 2.99",
        bowl: "16",
        orderType: "Dine In",
        category: "Soup",
    },
    {
        id: 10,
        image: "/Image-5.png",
        description: "Healthy noodle with spinach leaf ",
        price: "$ 3.29",
        bowl: "22",
        orderType: "To go",
        category: "Cold Dishes",
    },
    {
        id: 11,
        image: "/Image-5.png",
        description: "Hot spicy fried rice with omelet ",
        price: "$ 3.49",
        bowl: "13",
        orderType: "Delivery",
        category: "Hot Dishes",
    },
    {
        id: 12,
        image: "/Image-6.png",
        description: "Spicy instant noodle with special omelette ",
        price: "$ 3.59",
        bowl: "17",
        orderType: "To go",
        category: "Hot Dishes",
    },
];